# Exported from Render on 2025-03-25T14:06:20Z
services:
- type: web
  name: NHS_Project
  runtime: python
  repo: https://github.com/EneaK9/NHS_Project
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_NAME
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  region: oregon
  buildCommand: pip install --no-cache-dir -r requirements.txt
  startCommand: gunicorn -w 4 -b 0.0.0.0:8080 backend.main:app
  rootDir: backend/
version: "1"
